port: 8080
jwt_secret: my-secret-key

routes:
  - path: /users
    auth: true
    backends:
      - http://localhost:3001
      - http://localhost:3002
  - path: /orders
    auth: false
    backends:
      - http://localhost:3002
  - path: /slow
    auth: false
    backends:
      - http://localhost:3001
  - path: /products
    auth: false
    backends:
      - http://localhost:3001